language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="mint serde"

matrix:
  include:
    - rust: nightly
      env: CARGO_FEATURES="simd"
    - rust: nightly
      env: CARGO_FEATURES="serde simd"

script:
  - cargo build --features "$CARGO_FEATURES"
  - cargo test --features "$CARGO_FEATURES"
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo bench --features "$CARGO_FEATURES"
    fi
