[package]

name = "cgmath"
version = "0.3.1"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Pierre Krieger",
        "Tomasz Stachowiak"
]
license = "Apache-2.0"
description = "A linear algebra and mathematics library for computer graphics."

documentation = "http://bjz.github.io/cgmath-rs"
homepage = "https://github.com/bjz/cgmath-rs"
repository = "https://github.com/bjz/cgmath-rs"

keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]

[lib]
name = "cgmath"

[dependencies.rustc-serialize]
rustc_serialize = "*"

[dependencies]
num = "*"
rand = "*"
