[package]

name = "cgmath"
version = "0.12.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Pierre Krieger",
        "Tomasz Stachowiak"
]
license = "Apache-2.0"
description = "A linear algebra and mathematics library for computer graphics."

documentation = "https://docs.rs/cgmath"
homepage = "https://github.com/brendanzab/cgmath"
repository = "https://github.com/brendanzab/cgmath"
readme = "README.md"

keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]

[lib]
name = "cgmath"

[features]
unstable = []
default = ["rustc-serialize"]
eders = ["serde", "serde_derive"]

[dependencies]
approx = "0.1"
num-traits = "0.1"
rand = "0.3"
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "0.8", optional = true }
serde_derive = { version = "0.8", optional = true }

[dev-dependencies]
glium = "0.15"
serde_json = "0.8"
