[package]

name = "cgmath"
version = "0.14.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
license = "Apache-2.0"
description = "A linear algebra and mathematics library for computer graphics."

documentation = "https://docs.rs/cgmath"
homepage = "https://github.com/brendanzab/cgmath"
repository = "https://github.com/brendanzab/cgmath"
readme = "README.md"

keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]

[lib]
name = "cgmath"

[features]
unstable = []
eders = ["serde", "serde_derive"]
use_simd = ["simd"]

[dependencies]
approx = "0.1"
num-traits = "0.1"
rand = "0.3"
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
simd = { version = "0.2", optional = true }

[dev-dependencies]
glium = "0.16"
serde_json = "1.0"
