[package]

name = "cgmath"
version = "0.0.1"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>",
        "Brian Heylin",
        "Colin Sherratt",
        "Dzmitry Malyshau",
        "Erick Tryzelaar",
        "Luqman Aden",
        "Maik Klein",
        "Mikko Perttunen",
        "Tomasz Stachowiak"
]

[lib]
name = "cgmath"

[dependencies]
rustc-serialize="*"
rand_macros="*"
rand="*"