[package]

name = "cgmath"
version = "0.15.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
license = "Apache-2.0"
description = "A linear algebra and mathematics library for computer graphics."

documentation = "https://docs.rs/cgmath"
homepage = "https://github.com/brendanzab/cgmath"
repository = "https://github.com/brendanzab/cgmath"
readme = "README.md"

keywords = ["gamedev", "math", "matrix", "vector", "quaternion"]

[lib]
name = "cgmath"

[features]
unstable = []
swizzle = []

[dependencies]
approx = "0.1"
mint = { version = "0.4.1", optional = true }
num-traits = "0.1"
rand = "0.4"
serde = { version = "1.0", features = ["serde_derive"], optional = true }
simd = { version = "0.2", optional = true }

[dev-dependencies]
glium = "0.17"
serde_json = "1.0"
